services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod # Mandotroy for custom Dockerfile

    container_name: "chatapp_be_container"
    image: "chatapp_be_image"

    ports:
      - 80:5000

    environment:
      NODE_ENV: ${NODE_ENV}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      CLOUD_NAME: ${CLOUD_NAME}
      DB_URL: ${DB_URL}
      GEMINI_API: ${GEMINI_API}
      JWT_KEY: ${JWT_KEY}
      ORIGIN: ${ORIGIN}
      NODEMAILER_USER: ${NODEMAILER_USER}
      NODEMAILER_PASS: ${NODEMAILER_PASS}
