FROM node:20-alpine

WORKDIR /app

RUN addgroup app && adduser -S sysuser -G app

COPY package*.json .

RUN npm ci --only=production

COPY . .

RUN chown -R sysuser:app .

USER sysuser

EXPOSE 5000

CMD ["npm", "run", "start"]